version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  server:
    build:
      dockerfile: server/Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      mongo:
        condition: service_healthy

  client:
    build:
      dockerfile: client/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      mongo:
        condition: service_healthy