version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: db
    restart: always
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
